# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dominic Grimm
description: >- # this means to ignore newlines until "baseurl:"
  Musician and Composer
baseurl: "/" # the subpath of the site
url: "https://dominicgrimm.com" # the base hostname & protocol for the site
og_image:
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About
    - name: Music
      slug: https://thewanderingthistle.bandcamp.com/
    - name: Shows
    - name: Contact


footer:
  show_powered_by: false

  follow:
    - type: instagram
      name: Instagram
      link: https://www.instagram.com/thewanderingthistle/
    - type: youtube
      name: Youtube
      link: https://www.youtube.com/@TheWanderingThistle
    - type: bandcamp
      name: Bandcamp
      link: https://thewanderingthistle.bandcamp.com/
    - type: linktree
      name: Linktree
      link: https://linktr.ee/TheWanderingThistle

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
