# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: A Magpie's Hoard
description: >- # this means to ignore newlines until "baseurl:"
  Musician and Composer
baseurl: "/music" # the subpath of the site
url: "https://ruffledbirdling.github.io" # the base hostname & protocol for the site
og_image:
google_analytics:

header:
  pages:
    - name: Home
      slug: /
    - name: About
    - name: Music
    - name: Contact


footer:
  show_powered_by: false

  follow:
    - type: instagram
      name: Instagram
      link: https://www.instagram.com/ruffledbirdling/
    - type: youtube
      name: Youtube
      link: https://www.youtube.com/@ruffledBirdling/videos
    - type: bandcamp
      name: Bandcamp
      link: https://ruffledbirdling.bandcamp.com/
    - type: linktree
      name: Linktree
      link: https://linktr.ee/ruffledbirdling

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
